@baseUrl = http://localhost:3333

# @name register_restaurant
Post {{baseUrl}}/restaurants
Content-Type: application/json

{
  "restaurantName": "zulmira-sup",
  "name": "Mário César",
  "email": "silva@gmail.com",
  "phone": "9271571"
}

###

# @name send_auth_link
Post {{baseUrl}}/authenticate
Content-Type: application/json

{
  "email": "silva@gmail.com"
}

###

# @name authenticate_from_link
Get {{baseUrl}}/auth-links/authenticate