version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=pizzashop_node
    volumes:
      - pizzashop_node_data:/bitnami/postgresql

volumes:
  pizzashop_node_data:
